import type { Metadata } from "next";
import "./globals.css";
import { geistMono, InstrumentSans, jakarta, syne } from "@/fonts";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${InstrumentSans.className} ${syne.variable} ${jakarta.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute={"class"}
          enableSystem
          disableTransitionOnChange
          defaultTheme="light">
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
